### ISSUE TITLE
EventGrid Trigger support

### ISSUE THREAD

**Issue by alexeymarkov** [JamesRandall/FunctionMonkey#105]
Hi James,

are you going to add a support of EventGrid Triggers?
If not, I could implement and provide a PR.

Regards,
Alexey

**Comment by JamesRandall** [comment]
Will push out in beta later today.

**Comment by alexeymarkov** [comment]
I meant Event Grid, not Event Hub :-)

But do not care too much, I will try to add a support for Event Grid as well and provide a PR as soon as it is ready.

**Comment by JamesRandall** [comment]
That would be awesome thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
