### ISSUE TITLE
HTTP Trigger fails in the latest version 4.0.25-beta.1

### ISSUE THREAD

**Issue by alexeymarkov** [JamesRandall/FunctionMonkey#106]
Hi James,

I always get InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.ParameterExpression' to type 'MyAssembly.Commands.TestCommand' when trying to run a HTTP Trigger function.

The problem is in this line:
command = (MyAssembly.Commands.TestCommand)(await pluginFunctions.BindClaims(principal, command)); 

Something wrong with claims binders regardless of whether I configure it or not.

If the problem is unknown for you I could investigate and provide a fix.

Regards,
Alexey

**Comment by JamesRandall** [comment]
I'll take a look this weekend and release a new beta (including the cancellationtoken in your other issue).

**Comment by alexeymarkov** [comment]
Thank you!

Regarding CancellationToken pay attention there are two of them : one
injected into a function and another one from HttpContext.RequestAborted.
If you cancel a http request only the second is triggered which makes the
first useless IMHO. Maybe combining them into a single could be a solution
(for http and for signalr triggers). Have a look at
CancellationTokenSource.CreateLinkedTokenSource.

James Randall <notifications@github.com> schrieb am Fr., 20. Dez. 2019,
19:35:

**Comment by JamesRandall** [comment]
I've resolved this (commit 26991dc0caeacbe9bbbf8e76b415ef13c3814831) and added some test cases, should push out an update today / tomorrow.

Thanks for that info - will take a look!
