### ISSUE TITLE
CredentialProvider.VSS.exe should be installed as a package or installed via ps script

### ISSUE THREAD

**Issue by goblinfactory** [JamesRandall/FunctionMonkey#108]
Isn't it a huge security risk (and potentially a tricky licence issue ) to distribute the credential provider as an executable? Should we not rather install the provider as a package or at the very least a wget or similar powershell script so that users can verify the executable is coming from a trusted source? This package is available from the public package store so I dont think there's a chicken and egg problem here?

**Comment by JamesRandall** [comment]
Its not used, I think its just committed at some point by mistake. Deleted.
