### ISSUE TITLE
Build issue with FunctionMonkey.Compiler.targets

### ISSUE THREAD

**Issue by lbrecheisen** [JamesRandall/FunctionMonkey#110]
Upgrading to version _4.0.26-beta.2_, I'm getting the following build error in a project.

```
Could not execute because the specified command or file was not found.
  Possible reasons for this include:
    * You misspelled a built-in dotnet command.
    * You intended to execute a .NET Core program, but dotnet-/Users/lbrecheisen/.nuget/packages/functionmonkey.compiler/4.0.26-beta.2/build/netstandard1.0/..\..\tools\netcoreapp3.1\FunctionMonkey.Compiler.dll does not exist.
    * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
/Users/lbrecheisen/.nuget/packages/functionmonkey.compiler/4.0.26-beta.2/build/netstandard1.0/FunctionMonkey.Compiler.targets(18,5): error MSB3073: The command "dotnet "/Users/lbrecheisen/.nuget/packages/functionmonkey.compiler/4.0.26-beta.2/build/netstandard1.0/..\..\tools\netcoreapp3.1\FunctionMonkey.Compiler.dll" "/Users/lbrecheisen/Repos/call-service/App/bin/Debug/netcoreapp2.1/bin\Dialer.App.dll" --netcore21 --jsonoutput" exited with code 1. [/Users/lbrecheisen/Repos/call-service/App/Dialer.App.csproj]
```
I'm running macOS and noticed there is a mix of forward and back slashes in the above command.

I was able to get the following command to run successfully on its own after fixing the slashes.
```
dotnet "/Users/lbrecheisen/.nuget/packages/functionmonkey.compiler/4.0.26-beta.2/build/netstandard1.0/../../tools/netcoreapp3.1/FunctionMonkey.Compiler.dll" "/Users/lbrecheisen/Repos/call-service/App/bin/Debug/netcoreapp2.1/bin/Dialer.App.dll" --netcore21 --jsonoutput
```

**Comment by JamesRandall** [comment]
That's odd. I'm on a Mac too. What dev tool are you using?

I used to have the target branch based on OS and do slashes one way or the other but during my revamp of the MSBuild tool read that was no longer required and so removed that code. Tested on Mac and it was fine so thought... ok! Clearly not!

If you can let me know what tool you're using I'll try and replicate and fix.

**Comment by lbrecheisen** [comment]
I'm running vscode with the _ms-vscode.csharp_ extension installed.

```
dotnet --version
3.1.100
```
```
func --version
3.0.2009
```
Thanks for the help!

**Comment by JamesRandall** [comment]
I've restored the v3 method of working with paths in the targets and published that as part of beta 3 - its on NuGet now. Let me know if that helps!

I use Rider.

**Comment by lbrecheisen** [comment]
Looks good. Was able to build using beta 4.
