### ISSUE TITLE
Publishing issue

### ISSUE THREAD

**Issue by robcwaldron** [JamesRandall/FunctionMonkey#111]
Hi, on the latest beta, attempting to publish results in the error "The "InputAssemblyPath" parameter is not supported by the "ConvertErrors" task. Verify the parameter exists on the task, and it is a settable public instance property"

![image](https://user-images.githubusercontent.com/1562797/71763625-a5337900-2f29-11ea-847e-8c9a9440ef73.png)

I'm using .NET Core 3.1 and Functions 3.

**Comment by JamesRandall** [comment]
Was this from the command line on Windows?

**Comment by robcwaldron** [comment]
yep, this was on windows with VS Code.

**Comment by JamesRandall** [comment]
Ahh ok thank you. Someone else has reported a problem on Code on Mac.

I think I know what's wrong - I'll get a fix out in beta3 (which shouldn't be far off).

Thank you!

**Comment by robcwaldron** [comment]
No worries. Thanks for looking into it! Thankfully, there's a bit of a workaround where you can just ignore the error and continue the publish for the time being.

**Comment by mdg215199** [comment]
I was having the same issue, though, mine is happening w/in Azure Devops CI Pipeline.  I switched back to trying to use 3.0, and get an error where it couldn't locate service bus.

dotnet 3.1 error (matches error @robcwaldron 
![image](https://user-images.githubusercontent.com/39094712/71774030-820ec680-2f35-11ea-9b87-cc7fd8e3edae.png)


switched back to 3.0, and getting the following error now:
![image](https://user-images.githubusercontent.com/39094712/71774027-71f6e700-2f35-11ea-9421-b27e756cb86b.png)

Does anyone else using Azure CI?  Example of the CI yaml:
`trigger:
- develop
- staging
- uat
- master

pool:
  vmImage: 'windows-latest'

steps:
   
#install giversion nuget to assist with setting versions in place
# note, the released one doesnt work in ubuntu and has to be used using beta release of 5.0 
- script: |
    dotnet tool install --global GitVersion.Tool
  displayName: "GitVersion Setup and Run"

- task: DotNetCoreCLI@2 
  displayName: 'dotnet restore from feed' 
  inputs: 
    command: restore 
    projects: '**/*.csproj'
    vstsFeed: 'XXXXXXXXXXXXXX'
    # includeNuGetOrg: true 
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: 'src/MotionCX.WorkfloEventStore.FunctionTest/MotionCX.WorkfloEventStore.FunctionTest.csproj'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false


- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'

**Comment by JamesRandall** [comment]
I've restored the v3 method of working with paths in the targets and published that as part of beta 3 - its on NuGet now. Let me know if that helps!

**Comment by lbrecheisen** [comment]
I'm also getting the above publish error on beta 4.

**Comment by JamesRandall** [comment]
I believe this is now fixed in v4.0.44-beta.4  but any more issues give me a shout!
