### ISSUE TITLE
Upgrading from 4.0.29-beta.3 to 4.0.38-beta.4 error

### ISSUE THREAD

**Issue by mdg215199** [JamesRandall/FunctionMonkey#117]
Getting error while trying to upgrade.  Complaining that it can't find Newtonsoft.Json 11.0.0.  Before updating, build worked fine.  

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ConvertErrors" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at FunctionMonkey.Compiler.MSBuild.ConvertErrors.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	MotionCX.CRM.FunctionApp	C:\Users\mdgar\.nuget\packages\functionmonkey.compiler\4.0.29-beta.3\build\netstandard1.0\FunctionMonkey.Compiler.targets	26

**Comment by robcwaldron** [comment]
I can confirm this has happened to me as well

**Comment by alexeymarkov** [comment]
For me as well
It seems it tries to compile to a wrong target .NET Standard instead of .NET Core

**Comment by JamesRandall** [comment]
Thanks all - I have been looking at this, will update shortly!

**Comment by JamesRandall** [comment]
This error is coming from the MSBuild task that reports errors in MSBuild (its a netstandard project). Turns out in some scenarios their is an issue with Newtonsoft.Json 12 and in others with Newtonsoft.Json 11.

Easiest solution was to get rid of Newtonsoft.Json.

Will push out new packages some point in the next few days.

**Comment by JamesRandall** [comment]
I've just pushed out v4.0.39-beta.4 which I hope resolves this. Give it a whirl and let me know please :)

**Comment by alexeymarkov** [comment]
Hm, I cannot see the new release...

**Comment by JamesRandall** [comment]
Ahhh yes sugar I need to stamp GitHub. Done now!

**Comment by alexeymarkov** [comment]
Checked, now compiled successfully.
Thanx!

**Comment by JamesRandall** [comment]
Great! Phew.

Thanks for trying that!
