### ISSUE TITLE
SignalR Negotiate does not work anymore in 4.0.39-beta.4

### ISSUE THREAD

**Issue by alexeymarkov** [JamesRandall/FunctionMonkey#124]
It throw NullReferenceException at the line
`var tokenValidator = (FunctionMonkey.Abstractions.ITokenValidator)
FunctionMonkey.Runtime.ServiceProvider.GetService(typeof({{TokenValidatorTypeName}}));
principal = await tokenValidator.ValidateAsync(authorizationHeader);`
-> tokenValidator is null here.

I have to change it to
`var tokenValidator = (FunctionMonkey.Abstractions.ITokenValidator)				FunctionMonkey.Runtime.ServiceProvider.GetService(typeof(FunctionMonkey.Abstractions.ITokenValidator));`
to make it working.

I found comments in your code you are going to get rid of TokenValidatorType in FunctionDefinition. That is ok but would be great to have it fixed :-)

**Comment by alexeymarkov** [comment]
Even having fixed that it does not always work.
In 50% cases I have a runtime exception CreateJwtSecurityToken method cannot be found.
I replaces token generation with a code based on the example I pointer out in another SignalR issue and it works like a charm :-)

Here is the snippet for signalrcommandnegotiate.csharp.handlebars
`
public static IActionResult CreateSignalRResponse(FunctionMonkey.Commanding.Abstractions.SignalRNegotiateResponse commandResponse)
        {
            var connectionInfo = new SignalRConnectionInfo();
			var serviceManager = StaticServiceHubContextStore.Get("{{ConnectionStringSettingName}}").ServiceManager;
			connectionInfo.AccessToken = serviceManager
				.GenerateClientAccessToken(
					commandResponse.HubName,
					commandResponse.UserId);
			connectionInfo.Url = serviceManager.GetClientEndpoint(commandResponse.HubName);
			return new OkObjectResult(connectionInfo);
        }
`

**Comment by JamesRandall** [comment]
There were a few issues in their - I'd not got round to updating to use the pluginFunctions approach to things. Should be fixed in 4.0.52-beta.4.
