### ISSUE TITLE
[Compilation Error] Blob Storage function to Service Bus output binding

### ISSUE THREAD

**Issue by lbrecheisen** [JamesRandall/FunctionMonkey#134]
Using a blob function with an output binding to service bus,  I'm receiving the following error: 

`Error compiling function: BlobFnTest.cs(48,37): error CS0103`
`The name 'pluginFunctions' does not exist in the current context`

I'm utilizing the MediatR implementation.

The following code should reproduce the error.

Command: 
```c#
    public class TestCommand : IRequest<string>, IStreamCommand
    {
        public Stream Stream { get; set; } = Stream.Null;
        public string? Name { get; set; }
    }
```

Handler:
```c#
    internal class TestHandler : IRequestHandler<TestCommand, string>
    {
        public Task<string> Handle(TestCommand command, CancellationToken ct)
        {
            return Task.FromResult("test");
        }
    }
```

Configuration:
```c#
    .Storage(builder => builder
        .BlobFunction<TestCommand>("test-container/{name}")
            .OutputTo.ServiceBusTopic("test-topic"))
```

Packages Extensions:
```xml
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
```

Function Monkey Version: `4.0.56-beta.4`
Dotnet Version: `3.1`
Azure Function Core Tools Version: `3.0.2106`
Editor: `VSCode`
OS: `Mac`

**Comment by rturnq** [comment]
You have probably moved on by now, but I ran into this same issue. I dug into it and it appears `pluginFunctions` is not defined in the stream blob storage function template like it is in others. I created a pull request to resolve the issue: #163
