### ISSUE TITLE
JSON.NET DefaultContractResolver 

### ISSUE THREAD

**Issue by mcheruvu** [JamesRandall/FunctionMonkey#15]
Hello

Do you mind, turning off the CamelCasePropertyNamesContractResolver() in method - CreateResponse in the file: http.csharp.handlebars?

So that we can change the JSON.NET default DefaultContractResolver to apply a different behavior for all the API.

Thanks
Kris

**Comment by JamesRandall** [comment]
I'll take a look at it - certainly agree that would make sense but I've a (possibly unfounded) feeling that I did that for a reason... will take a look!

**Comment by mcheruvu** [comment]
Thank you, James, for the response.

I did try this but it did work only during the code generation and also for the Open API. However it did not take effect in actual azure functions, I can see that the entry point is different and JSON.NET defaulted back to CamelCase.

My proposal to fix this is:

1. Remove any specific JSON contract resolvers, mainly in the CreateResponse method
2. Allow some kind of bootstrap method (anonymous) method for any initiation logic during the setup method:

 builder
                .Setup((serviceCollection, commandRegistry) =>
                {
                    serviceCollection.AddLogging();
                    serviceCollection.AddOptions<SecuritySettings>();

                    serviceCollection.AddTransient<IValidator<LoginCmdInput>, LoginCmdInputValidator>();
                    commandRegistry.Register<LoginCmdHandler>();
                    **
                    JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
                    {
                        ContractResolver = new DefaultContractResolver
                        {
                            NamingStrategy = new SnakeCaseNamingStrategy(),
                        },
                        NullValueHandling = NullValueHandling.Ignore
                    };
                    **
                })

I have tried this but this code did not get added into the function code generation.

Perhaps, a new method to facilitate this:

**.FunctionBootstrap( ** () => {
                   ** //or call another helper class/method and this logic will be ported to azure function static constructor**
                    JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
                    {
                        ContractResolver = new DefaultContractResolver
                        {
                            NamingStrategy = new SnakeCaseNamingStrategy(),
                        },
                        NullValueHandling = NullValueHandling.Ignore
                    };
                    
                })
  
Thanks
Kris

**Comment by JamesRandall** [comment]
I've got a solution for this under development - hopefully drop in a few days.

Apologies it took me a while, I've been snowed under with client work.

**Comment by mcheruvu** [comment]
Thank you, very much

**Comment by JamesRandall** [comment]
Hopefully you'll find what you need in the enhancements I've just pushed to NuGet in v0.18.1

https://functionmonkey.azurefromthetrenches.com/guides/crosscutting/serialization.html

**Comment by mcheruvu** [comment]
Thank you
