### ISSUE TITLE
Compiler Build Error with Entity Framework Core

### ISSUE THREAD

**Issue by peteharrison** [JamesRandall/FunctionMonkey#167]
I'm trying to add Entity Framework Core to my Function Monkey function app and am getting a build error in the compiler as per the following..

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | Unexpected error: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.   at Cadence.Symphony.Auth.FunctionAppConfiguration.Build(IFunctionHostBuilder builder)   at FunctionMonkey.Compiler.Core.Compiler.Compile() in /Users/jamesrandall/code/functionMonkey/library/Source/FunctionMonkey.Compiler.Core/Compiler.cs:line 91   at FunctionMonkey.Compiler.Program.Main(String[] args) in /Users/jamesrandall/code/functionMonkey/library/Source/FunctionMonkey.Compiler/Program.cs:line 56 | Cadence.Symphony.Auth | C:\Users\peter.harrison.CADENCESOFTWARE\.nuget\packages\functionmonkey.compiler\4.0.56-beta.4\build\netstandard1.0\FunctionMonkey.Compiler.targets | 29 |

**Comment by AKomyshan** [comment]
What version of Function Monkey do you use?

**Comment by peteharrison** [comment]
> What version of Function Monkey do you use?

I was using the latest beta version v4.0.56-beta.4

What should I be using? I followed all of the instructions on the getting started page and had everything working fine until I tried to add entity framework dependency injection via the function app configuration... On thinking about this, is the Function Monkey IFunctionAppConfiguration only to be used to put DI for Function Monkey specific things and if I want to inject other services I.e. Entity Framework then I should use the standard Microsoft Dependency Injection Function Startup? Maybe that is where I am going wrong?

**Comment by AKomyshan** [comment]
I am using the same version of the package. And also i see:
![image](https://user-images.githubusercontent.com/8322307/90341829-965a8c00-e00b-11ea-9c54-98c751178f3f.png)

Im not sure but maybe problem in `Microsoft.NET.Sdk.Functions` package. Which version of Microsoft.NET.Sdk.Functions are you using?

**Comment by peteharrison** [comment]
Ok so I worked it out!
The issue was that I was trying to inject entity framework core using the Function Monkey IFunctionAppConfiguration builder. You actually need to register other dependencies through the standard Startup.cs dependency injection.. as per below.

using FunctionMonkeyTest.Models;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;


[assembly: FunctionsStartup(typeof(FunctionMonkeyTest.Startup))]

namespace FunctionMonkeyTest
{
    class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            string SqlConnection = Environment.GetEnvironmentVariable("AuthDBConnectionString");
            builder.Services.AddDbContext<AuthDBContext>(
                options => options.UseSqlServer(SqlConnection));
        }
    }
}
