### ISSUE TITLE
Guid? not binding from query parameter

### ISSUE THREAD

**Issue by JamesRandall** [JamesRandall/FunctionMonkey#17]
Probably applies to other value types too.

**Comment by AKomyshan** [comment]
Please take a look [my PR](https://github.com/JamesRandall/FunctionMonkey/pull/37). This fixes a problem with binding Nullable value. If you have any comments or suggestions please let me know.

I hope that helps.

**Comment by JamesRandall** [comment]
Thank you - I'll be in Function Monkey later so will look to get this merged, many thanks!

**Comment by JamesRandall** [comment]
PR merged - thank you!
