### ISSUE TITLE
Unable to access db connection string

### ISSUE THREAD

**Issue by mcheruvu** [JamesRandall/FunctionMonkey#18]
Hello

I am trying to get the connection string through IOptions.

 builder
                .Setup((serviceCollection, commandRegistry) =>
                {
                    serviceCollection.AddLogging();
                                        
                    //serviceCollection.AddOptions();

                    serviceCollection.AddOptions<DbSettings>("DbSettings");

....
....

DbSettings is defined in local.settings.json.

However, when I access this through the constructor of the command handler, the value is coming as null.

Any help is appreciated.

Thanks
Kris

**Comment by mcheruvu** [comment]
Thank you, James.

I need to access the connection string from the localsettings.json file. If I can access it from the execution context, that will be great, as I am not sure how to do that.

I have tried the way  you mentioned already and since the function configuration is the entry point for the functions, all the settings will not take effect. We basically need some bootstrapping that can happen at the function constructor level.

Hope I am clear in my request.

Thank you
Kris

**Comment by KarachentsevDanil** [comment]
> I've generally kept this lightweight with Environment.GetEnvironmentVariable(...) and you might need to do a little more setup to use IOptions. I'll see if I can knock up a sample but I assume it will be something like this:
> 
> var config = new ConfigurationBuilder()
> .SetBasePath(functionAppDirectory)
> .AddJsonFile("local.settings.json")
> .AddEnvironmentVariables()
> .Build();
> 
> Will need to have a think about where to get the functionAppDirectory as I've generally seen this retrieved using the ExecutionContext - which I have but its not passed into the setup at the moment, I may make a small modification to enable this.

Hi, when you will make this small modification?

**Comment by rameshjanjyam** [comment]
Hi. Is this available now?
I am planning to use azure app configuration -https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app - so i think I require this change implemented to use the configuration builder.

**Comment by JamesRandall** [comment]
I'll take a look as part of 2.1 that I am working on now.

**Comment by davidjsteele** [comment]
Hi James, 
Any update on this in regards to "functionAppDirectory" executionContext - looking to read config on "startup".
Many thanks

**Comment by davidjsteele** [comment]
Apologies, realised can be accomplised, for local dev anyway, with

**Comment by willjr20** [comment]
Hi James,

What is the proper way to read a local.setting.json file within FunctionMonkey?

Thanks,

William

**Comment by willjr20** [comment]
Hi Again,

I figured this out using Environment variables.  Something like

`            // TEST:: Get value from env variable.
            var environmentVariable = Environment.GetEnvironmentVariable("DataBaseConnection");`

Thanks,

William
