### ISSUE TITLE
Errors in several handlebars templates

### ISSUE THREAD

**Issue by abezverkov** [JamesRandall/FunctionMonkey#22]
First.  I love this project!  

I dont know if I am doing something wrong, or missing something, but:  
When I try to compile with timer or queue functions, it fails during the FunctionMonkeyCompiler, complaining: `The type or namespace name 'ValidationException' does not exist in the namespace 'FunctionMonkey.Abstractions.Validation'`.  I searched through the repo and found that class in `FunctionMonkey.Commanding.Abstractions.Validation` (Commanding added), pulled, changed the templates and recompiled.  

timer.csharp.handlebars
servicebusqueue.csharp.handlebars
servicebussubscription.csharp.handlebars
eventhubqueue.csharp.handlebars
storageblob.csharp.handlebars
storagequeue.csharp.handlebars

That error went away, but then it started complaining about `messageId` not being found.  It seems `messageId` made it into some of the validation exception messages where it wasnt defined in the method signature.  

timer.csharp.handlebars
eventhubqueue.csharp.handlebars
storageblob.csharp.handlebars
storagequeue.csharp.handlebars

**Comment by JamesRandall** [comment]
Thanks for reporting this and investigating it so thoroughly.

The short version of what had happened is that I'd done something really stupid. The longer version is that I seem to have embarked on a misguided copy and paste between templates early one morning on a train before coffee and not properly finished what I was doing. Mea culpa.

I've just uploaded v0.18.6 of FunctionMonkey.Compiler to NuGet which should resolve this. And I've got some integration tests on the way that should catch these things going forwards. When I set off writing this I had no real idea how it was going to work never mind how I was going to test it!

If you find any further issues please do let me know. I'm aiming to get the library to a v1.0.0 in the next few weeks so am prioritising bug fixes (and those tests).
