### ISSUE TITLE
Blobs storage trigger throws exception during compilation

### ISSUE THREAD

**Issue by imkheong** [JamesRandall/FunctionMonkey#23]
When attempting to build a Function App 2 project configured for blob trigger, it fail while building.

Using Visual Studio 2017 Version 15.8.2. Azure Functions and Web Jobs tools 15.10.2046.0.

Source code on Github [here](https://github.com/imkheong/FunctionMonkeyBlobTest).

Error screenshot
![image](https://user-images.githubusercontent.com/6950029/49521329-2e6c1c80-f8e0-11e8-8edf-f04eb43a3905.png)

> 1>------ Build started: Project: BlobFunctionAppTest, Configuration: Debug Any CPU ------
> 1>BlobFunctionAppTest -> D:\Playground\Azure > FunctionMonkey\FunctionMonkeyBlobTest\BlobFunctionAppTest\bin\Debug\netcoreapp2.0\bin\BlobFunctionAppTest.dll
> 1>
> 1>Unhandled Exception: FunctionMonkey.ConfigurationException: CS0246:The type or namespace name 'Uri' could not be found (are you missing a using directive or an assembly reference?) > SourceFile([518..521))CS0012:The type 'Uri' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.Uri, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. SourceFile([1842..1870))
1>   at FunctionMonkey.Compiler.Implementation.AssemblyCompiler.CompileAssembly(IReadOnlyCollection`1 syntaxTrees, IReadOnlyCollection`1 externalAssemblyLocations, OpenApiOutputModel openApiOutputModel, String outputBinaryFolder, String outputAssemblyName, String assemblyNamespace, TargetEnum target)
1>   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in C:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Implementation\FunctionCompiler.cs:line 94
1>   at FunctionMonkey.Compiler.Program.Main(String[] args) in C:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Program.cs:line 47

What might be the problem that is happening here?

Note: I used the output source in place of FunctionAppConfiguration, it worked as expected.

**Comment by JamesRandall** [comment]
Thanks for reporting this - I believe its an issue with how an assembly is resolved for Roslyn and am just working on a fix now.

**Comment by JamesRandall** [comment]
I was able to replicate this using your provided source (thank you very much for that) and then resolve it. v0.18.7 of FunctionMonkey.Compiler is indexing in NuGet at the moment.

Any more issues please let me know, and thanks again!
