### ISSUE TITLE
Publish fails with FunctionMonkey.ConfigurationException: CS1705

### ISSUE THREAD

**Issue by abezverkov** [JamesRandall/FunctionMonkey#24]
After I updated to 0.18.6 which fixed all my other problems, my VSTS build started failing.  Im using the standard function app deployment template which does a build and publish.  
I noticed that it passed running the 'after build' compile, but failed the 'after publish' compile with the error:
`FunctionMonkey.ConfigurationException: CS1705:Assembly 'FunctionApp3' with identity 'FunctionApp3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' SourceFile([3106..3147))`
I get the same error running the dontnet command from the command line.  

After some digging  I saw that in `FunctionMonkey.Compiler.targets`, you are differentiating the `FunctionCompilerParams` for dotnetcore and adding --netcore21.  That is not being done for `FunctionPublishParams`.   

Adding that flag to the command line seems to fix the error, but I don't have a way to do that from my VSTS build.

**Comment by JamesRandall** [comment]
Thanks for reporting this - just working on a fix now. Your suggestion is spot on - I need that param on the publish step too. Just working on a fix now.

**Comment by JamesRandall** [comment]
I was able to replicate this and resolve it - 0.18.7 of FunctionMonkey.Compiler is indexing in NuGet at the moment and should resolve it. Let me know if you have any other issues and thanks again!
