### ISSUE TITLE
Ability to access raw input of function

### ISSUE THREAD

**Issue by JamesRandall** [JamesRandall/FunctionMonkey#3]
As per this tweet here:

https://twitter.com/MyMemoryLeaks/status/1017446734744702976

**Comment by JamesRandall** [comment]
A little behind but I've been looking at this. I already allow raw blobs to be accessed by a stream - which you access by decorating your command with a IStreamCommand interface. My proposal is to extend this out over the other function types.

**Comment by Trhymond** [comment]
It is awsome project.  We are looking into using this on one our projects. Is it possible to get the Request Header accessible from the command handler? Also is it possible to return different Http Status Codes?

**Comment by JamesRandall** [comment]
Thanks.

I'm actually looking at headers at the moment. I'm probably going to expose them on the IContextProvider interface rather than serialize commands from them. The latter seemed to get complex quickly.

Regarding HTTP status codes  - that's limited at the moment but its on my backlog.

**Comment by Trhymond** [comment]
Thank you very much. I will test it out and let you know

Tomy Rhymond

**Comment by JamesRandall** [comment]
@Trhymond - header binding is now available too in the latest release

**Comment by JamesRandall** [comment]
Took me a while to get to it but you can also now get hold of the request body by implementing the IStreamCommand interface on a command.
