### ISSUE TITLE
IHttpResponseHandler can't override response from ValidationResult. 

### ISSUE THREAD

**Issue by magoja2** [JamesRandall/FunctionMonkey#30]
I am using FluentValidation in my project.
I have created my own IHttpResponseHandler and i have noticed that ValidationResult can't be overridden because generated code doesn't call it.

![capture](https://user-images.githubusercontent.com/13003281/50444954-089ccb00-0914-11e9-98a1-8b55ba1b32b7.PNG)

**Comment by JamesRandall** [comment]
Thanks for reporting this - yes that looks wrong, I'll look to get a fix out.

**Comment by JamesRandall** [comment]
This is included in the 1.0 release that I'll be pushing to NuGet shortly.

**Comment by magoja2** [comment]
Thank you :)

**Comment by JamesRandall** [comment]
Took me a while as it was super fiddly getting things right in the template and I wanted to have a decent set of tests around it first. Should drop tonight or tomorrow.
