### ISSUE TITLE
IHttpResponseHandler isn't compatible with ICommand commands without result.

### ISSUE THREAD

**Issue by magoja2** [JamesRandall/FunctionMonkey#31]
if projects has a command with ICommand without TResult
###
public class UpdateCatalogCommand : ICommand
###
Project isn't compiled. It says:

Unhandled Exception: FunctionMonkey.ConfigurationException: CS0311:The type 'Todd.IO.Catalog.WebApi.Commands.UpdateCatalogCommand' cannot be used as type parameter 'TCommand' in the generic type or method 'ExceptionResponseHandler.CreateResponse<TCommand, TResult>(TCommand, TResult)'. There is no implicit reference conversion from 'Todd.IO.Catalog.WebApi.Commands.UpdateCatalogCommand' to 'AzureFromTheTrenches.Commanding.Abstractions.ICommand<FunctionMonkey.Abstractions.ISerializer>'. SourceFile([4580..4610))CS0311:The type 'Todd.IO.Catalog.WebApi.Commands.DeleteCatalogCommand' cannot be used as type parameter 'TCommand' in the generic type or method 'ExceptionResponseHandler.CreateResponse<TCommand, TResult>(TCommand, TResult)'. There is no implicit reference conversion from 'Todd.IO.Catalog.WebApi.Commands.DeleteCatalogCommand' to 'AzureFromTheTrenches.Commanding.Abstractions.ICommand<FunctionMonkey.Abstractions.ISerializer>'. SourceFile([4159..4189))
4>   at FunctionMonkey.Compiler.Implementation.AssemblyCompiler.CompileAssembly(IReadOnlyCollection`1 syntaxTrees, IReadOnlyCollection`1 externalAssemblyLocations, OpenApiOutputModel openApiOutputModel, String outputBinaryFolder, String outputAssemblyName, String assemblyNamespace, TargetEnum target)
4>   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey.Compiler/Implementation/FunctionCompiler.cs:line 94
4>   at FunctionMonkey.Compiler.Program.Main(String[] args) in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey.Compiler/Program.cs:line 47

**Comment by JamesRandall** [comment]
Thanks for reporting this - should now be fixed.
