### ISSUE TITLE
No job functions found. Try making your job classes and methods public.

### ISSUE THREAD

**Issue by nugosu** [JamesRandall/FunctionMonkey#32]
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

Azure Functions Core Tools (2.3.199 Commit hash: fdf734b09806be822e7d946fe17928b419d8a289)
Function Runtime Version: 2.0.12246.0

Forked the repo and added as existing projects then created reference built and played.

This is because I wan to update the microsoft azure document db core library and potentially the microsoft extensions dependency injection library.

Looks like I only have function monkey compiler  0.18.6-beta000 but my nuget package is  0.18.7-beta000. Not sure how to update my codes.

**Comment by nugosu** [comment]
The functions are not building in the bin file there is a complier targets file but no function folders.

**Comment by JamesRandall** [comment]
That's very odd. Normally this occurs if the FunctionMonkey.Compiler package hasn't been added.

Is the class that implements IFunctionAppConfiguration public?

If your source is in GitHub I'll happily take a look.

**Comment by JamesRandall** [comment]
Closing this as I can't replicate. If it continues to be an issue please let me know.
