### ISSUE TITLE
Enum property doesn't bind from query parameter.

### ISSUE THREAD

**Issue by cooller-94** [JamesRandall/FunctionMonkey#38]
I've created a simple program to demonstrate it.
There is the following enum.

`public enum SortOrder`
`{`
`	Ascending = 1,`
`	Descending = 2`
`}`

and command:

`public class EnumCommand : ICommand<string>`
`{`
`	public SortOrder Order { get; set; }`
`}`

For all requests below, the Order field is alwayws 0.

http://localhost:7071/api/Enum?Order=Descending
http://localhost:7071/api/Enum?Order=Ascending
http://localhost:7071/api/Enum?Order=1
http://localhost:7071/api/Enum?Order=2

Do you have any suggestions why this doesn't work?

**Comment by JamesRandall** [comment]
I've probably missed something in the query parameter binding code. I'll be in there later today so will look to get a fix out.

**Comment by AKomyshan** [comment]
Hi James, I see it very similar to #17 . While I was researching this, I found a solution. [ Just gentle desire to help ](https://github.com/JamesRandall/FunctionMonkey/pull/39) (#39)

Thank you for this wonderful project.
