### ISSUE TITLE
dotnet quit unexpectedly

### ISSUE THREAD

**Issue by StickNitro** [JamesRandall/FunctionMonkey#42]
I get this when trying to use `FunctionMonkey` with the following assemblies

Cosmonaut v2.9.0
Microsoft.Azure.DocumentDB.Core v2.2.2
Microsoft.Azure.WebJobs.Extensions.CosmosDB v3.0.3
Microsoft.Azure.WebJobs.Extensions.SignalRService v1.0.0-preview1-10025
Microsoft.NET.Sdk.Functions v1.0.24

I believe this is related to a assembly version conflict with the `Microsoft.Azure.DocumentDB.Core` assembly and I am unable to downgrade due to the other package that I am using

Any ideas when you can bring the references more up to date?

**Comment by JamesRandall** [comment]
Let me have a look - bumping them up should be fine.

**Comment by JamesRandall** [comment]
v0.22.0 targets the latest packages so hopefully thatr will get you going!
