### ISSUE TITLE
Reflection type exception when compiling function project

### ISSUE THREAD

**Issue by tomfalk** [JamesRandall/FunctionMonkey#5]
Hi there,

I've been testing Function Monkey on a new project and I think it's great.  However, I've run into an issue a couple of times now when trying to incorporate some Cosmos DB stuff.  I managed to resolve it the last time by changing package versions, but thought I'd post it this time as I'm struggling to get past it this time.  Not sure if you can help.

Error -

The command "dotnet "C:\Users\Administrator\.nuget\packages\functionmonkey.compiler\0.10.2-beta000\build\netstandard1.0\..\..\tools\netcoreapp2.0/FunctionMonkey.Compiler.dll" "D:\GitHub\letsbuildit\src\LetsBuildIt.Web.API.FM\bin\Debug\netstandard2.0\bin\LetsBuildIt.Web.API.FM.dll"" exited with code -532462766.	LetsBuildIt.Web.API.FM	C:\Users\Administrator\.nuget\packages\functionmonkey.compiler\0.10.2-beta000\build\netstandard1.0\FunctionMonkey.Compiler.targets	10	

Output: 

1>Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
1>   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
1>   at System.Reflection.Assembly.GetTypes()
1>   at FunctionMonkey.ConfigurationLocator.FindConfiguration(Assembly assembly) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey\ConfigurationLocator.cs:line 78
1>   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Implementation\FunctionCompiler.cs:line 56
1>   at FunctionMonkey.Compiler.Program.Main(String[] args) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Program.cs:line 45
1>C:\Users\Administrator\.nuget\packages\functionmonkey.compiler\0.10.2-beta000\build\netstandard1.0\FunctionMonkey.Compiler.targets(10,5): error MSB3073: The command "dotnet "C:\Users\Administrator\.nuget\packages\functionmonkey.compiler\0.10.2-beta000\build\netstandard1.0\..\..\tools\netcoreapp2.0/FunctionMonkey.Compiler.dll" "D:\GitHub\letsbuildit\src\LetsBuildIt.Web.API.FM\bin\Debug\netstandard2.0\bin\LetsBuildIt.Web.API.FM.dll"" exited with code -532462766.

**Comment by JamesRandall** [comment]
Thanks for letting me know. I should be releasing a new version shortly and I'll see if I can get in a better output for the ReflectionTypeLoadException. In the meantime:

Do you know what version of the Cosmos package you are using? I'm using it with Cosmos at the moment with the following pacakges:

Microsoft.Azure.DocumentDB.Core - 2.0.0-preview
Gremlin.Net - 3.4.0-rc1

**Comment by tomfalk** [comment]
That's the odd thing in this case - I had it previously when using a lower version of DocumentDB.Core, but I'm now using the 2.0.0-preview.  It's actually in a separate (local) project I'm referencing from the FM one this time, so it could be some other references causing the problem...  I'm working to see if I can narrow it down further.

**Comment by JamesRandall** [comment]
I have the same project setup. Are you using any of the Azure Storage libraries? Last I heard they were still problematic even with the binding improvements the Functions team had made.

I've just got a bit of testing to do on one of the upcoming features and I'll try and push out something with a more specific error message. In the meantime if you do manage to track it down please do let me know!

**Comment by tomfalk** [comment]
Nope, I'm not using any Azure Storage libraries.  I've made a little bit of progress with this...I'm not sure if any of this will be helpful though... but it looks like it's happening when I use DocumentClient directly in a command handler - e.g. with the following line:

Document testDocument = await _documentClient.CreateDocumentAsync(collectionUri, testItem);

I'm pretty sure this was working before I added another project locally which also uses the DocumentDB.Core libraries.  I'm able to use other classes from this project though.  I don't actually need to reference DocumentClient directly in the functions now so this isn't blocking me.  

I'll happily try it again when you push out the changes, just to see what is actually causing it.

Thanks for your help & the work you're doing on this library.  It makes writing functions a breeze (and fun!)

**Comment by JamesRandall** [comment]
v0.11 is available in NuGet which amongst a couple of other small enhancements gives more meaningful error information if this occurs again.

I'll close this for now but if you encounter any other issues please do let me know. Super appreciate the feedback!
