### ISSUE TITLE
Improved MSBuild Integration

### ISSUE THREAD

**Issue by JamesRandall** [JamesRandall/FunctionMonkey#50]
Currently the Function Monkey compiler runs as a console app invoked via a target in the MSBuild chain. When an error is encountered it throws out an exception that gets logged in the output window but its really less than ideal - on Mac or Linux you can also end up with a system style dotnet exception.

I'd like to wrap the compiler in an MSBuild task that better integrates into the build chain.

https://docs.microsoft.com/en-us/visualstudio/msbuild/task-writing?view=vs-2017

Not something I've done before, if anyone has any best practice or hints and tips I'd love to hear them.

**Comment by wynandjordaan** [comment]
@JamesRandall I am willing to help with this, we are also looking into this for another project.

**Comment by JamesRandall** [comment]
Great thank you.

Do you have any good jumping off points (simple reference apps etc.) for building one of these tasks and/or recommendations for development workflow? It strikes me its one of those things that might get quite slow to build if you get that wrong.

In terms of a PR type contribution - the compiler has a pretty simply entry point that you can find here:

https://github.com/JamesRandall/FunctionMonkey/blob/master/Source/FunctionMonkey.Compiler/Program.cs

Essentially it is provided the path to the assembly that contains the _IFunctionAppConfiguration_ implementation and a flag that tells it if its a net core DLL (if this flag isn't set it assumes its a netstandard DLL).

Its inserted into the build environment through NuGet and this targets file:

https://github.com/JamesRandall/FunctionMonkey/blob/master/Source/FunctionMonkey.Compiler/FunctionMonkey.Compiler.targets

I can easily pull FunctionMonkey.Compiler in two (this entry point and then an assembly containing the implementation). In my head the build task would then reference this second assembly and get inserted / registered in the build chain in a somewhat similar way to the existing console app.

**Comment by JamesRandall** [comment]
Implemented!
