### ISSUE TITLE
OpenAPI not adding backslash to URLs

### ISSUE THREAD

**Issue by likwidgames** [JamesRandall/FunctionMonkey#56]
Using the default host.json configuration below. Functions all work great through postman, but when trying to execute through OpenAPI site, it is not adding a backslash to the URL after the domain/port:

**Request URL**
http://localhost:7071api/v1/todo?status=active

TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from http://localhost:7071api/v1/todo?status=active
--

**host.json:**

`{
  "version": "2.0",
  "extensions": {
    "http": {
      "routePrefix": ""
    }
  }
}`

**Function:**
`.Functions(functions => functions
.HttpRoute("/api/v1/HelloWorld", route => route
                        .HttpFunction<HelloWorldCommand>()
                    )
                    .HttpRoute("/api/v1/todo", route => route
                        .HttpFunction<GetTodoQuery>(HttpMethod.Get)
                        .HttpFunction<GetTodoByIdQuery>("/{id}", HttpMethod.Get)
                        .HttpFunction<CreateTodoCommand>(HttpMethod.Post)
                       .HttpFunction<MarkTodoAsCompleteCommand>("/complete", HttpMethod.Put)
                            .OpenApiDescription("this is a test")
                    )
                );`

**Comment by tkrofta** [comment]
+1 - while postman working well, any hints or workaround to being able to test with swagger appreciated.

**Comment by vip32** [comment]
also the /api part is missing from the swagger url

![image](https://user-images.githubusercontent.com/164303/57222891-91372080-7004-11e9-85fc-88a1b2efd588.png)

![image](https://user-images.githubusercontent.com/164303/57222906-9c8a4c00-7004-11e9-9a40-7e787b129266.png)

**Comment by vip32** [comment]
is there any known workaround for this issue?

**Comment by JamesRandall** [comment]
I don't think there's a workaround but I'll try and take a look today - I think the fix should be fairly simple.

**Comment by JamesRandall** [comment]
This should all be resolved in v2.1.1 that is indexing in NuGet now.

Thanks for raising.

**Comment by vip32** [comment]
yes @JamesRandall, it is fixed now. many thanks!
