### ISSUE TITLE
Generated OpenApi definition not treating nullable value types as optional.

### ISSUE THREAD

**Issue by abezverkov** [JamesRandall/FunctionMonkey#58]
Looks like maybe you tried to address this in Issue#7.  Regardless: In the generated open api descriptions nullable types show up as required.  The problem is HttpParameter.IsOptional is being set to !type.IsValueType ... and unfortunately Nullable<T> returns true there.

**Comment by JamesRandall** [comment]
Thanks - I'll get that fixed.

**Comment by JamesRandall** [comment]
Addressed in v3.0.4-beta1. Thanks!
