### ISSUE TITLE
Optional Route Parameters

### ISSUE THREAD

**Issue by MrBliz** [JamesRandall/FunctionMonkey#7]
Nice project, will write  blog post on it when time allows.

I know that the docs say route parameters are not optional, but is this going to be a permanent limitation?

**Comment by JamesRandall** [comment]
Thanks. I don't plan on it being a permanent limitation - its more just time and getting round to it!

**Comment by MrBliz** [comment]
Cool, what’s your workaround? I’ve just being making optional params nullable, but then they don’t show up in swagger...

**Comment by JamesRandall** [comment]
Generally I've defined two routes:

.../myroute
.../myroute/{param}

And thats worked for me as they've made use of different commands. Other than that I think you'd need to use a query parameter.

I am planning to do some work on Function Monkey in the next few days. Can you give me a couple of example routes you'd like to use and if I get a chance I'll see if I can work that in.

**Comment by MrBliz** [comment]
The biggest use case I have for optional params is for paging, sorting and filtering where there might be multiple optional parameters eg: filter, page number, page size, sort column, sort direction.

**Comment by adam-short** [comment]
@MrBliz wouldn't that be done via query parameters?

**Comment by MrBliz** [comment]
Maybe i'm missing something, but how do you use Query Parameters here? You need to supply an ICommand to the HttpFunctionBuilder?

**Comment by JamesRandall** [comment]
It should “just work” for GET and DELETE verbs, there should be some docs in the section on routing:
https://functionmonkey.azurefromthetrenches.com/guides/http/routing.html

**Comment by MrBliz** [comment]
Re: Query Parameters

If i have the following class 

   ```
 public class EventListQuery
    {

        public int PageNumber { get; set; }
        public int PageSize { get; set; }
        public string Filter { get; set; }
        public bool Descending { get; set; }

        /// <summary>
        ///  Sortable Columns : Name, EventDate
        /// </summary>
        public string SortColumn { get; set; }
    }
```

In Swagger using Function Monkey the propertis are marked as required.

![image](https://user-images.githubusercontent.com/405011/46245048-d4cb0b80-c3df-11e8-837b-4f5a724b896d.png)

If use the same class in a non function monkey project

The properties are all optional, i have to explicitly set them as [Required]

![image](https://user-images.githubusercontent.com/405011/46245084-5b7fe880-c3e0-11e8-97a1-4f6d214032d7.png)

**Comment by JamesRandall** [comment]
I think it’s “just” an OpenApi doc issue - the way the parameter mapping works any parameters you don’t specify will just get the default values from your classes constructor.

I’ll fix the issue with the doc gen, let me know if you find they are actually required in practice as that would be a nasty bug!

I can’t remember if it was yourself looking for header binding but that’s nearly complete now.

**Comment by JamesRandall** [comment]
Optional route parameters now work and are in the imminent v1.0.0 release. They follow the approach documented here:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#customize-the-http-endpoint
