### ISSUE TITLE
OpenApi generation process doesn't support AuthorizationLevel.Function for Commands

### ISSUE THREAD

**Issue by sparkitny** [JamesRandall/FunctionMonkey#71]
Hi,

during the generation process for OpenApi it's not possible generate query parameter **code**  for Azure Functions with AuthorizationLevel.Function. In queries it's generally not a problem, because (although not very nice) a code parameter can easily be added. But in POST and PUT scenarios the swagger ui is not usable, when the azure functions is deployed. It's because the **code** parameter cannot be set in Post/Put. There're tools like Postman to replace ui, but for a quick manual testing it's useful to have a gui for.

**Comment by JamesRandall** [comment]
Agreed - it should form part of the Swagger and it shouldn't be a difficult change. I've added it to my backlog for the upcoming release.

**Comment by sparkitny** [comment]
Thanks.

**Comment by JamesRandall** [comment]
Addressed in v3.0.4-beta1. Thanks!
