### ISSUE TITLE
Compilation error when using service bus queue output binding

### ISSUE THREAD

**Issue by Cheranga** [JamesRandall/FunctionMonkey#74]
Hi,
I am trying to implement an HTTP triggered function which has an output binding to a service bus queue. When I add the code in the function configuration to do this I get the below compilation error. Can somebody please let me know what I'm doing wrong here?

`Unhandled Exception: FunctionMonkey.ConfigurationException: CS0246:The type or namespace name 'ServiceBusAttribute' could not be found (are you missing a using directive or an assembly reference?) SourceFile([866..876))CS0246:The type or namespace name 'ServiceBus' could not be found (are you missing a using directive or an assembly reference?) SourceFile([866..876))CS0246:The type or namespace name 'EntityType' could not be found (are you missing a using directive or an assembly reference?) SourceFile([884..894))CS0234:The type or namespace name 'ServiceBus' does not exist in the namespace 'Microsoft.Azure.WebJobs' (are you missing an assembly reference?) SourceFile([895..929))CS0246:The type or namespace name 'Connection' could not be found (are you missing a using directive or an assembly reference?) SourceFile([948..958))
   at FunctionMonkey.Compiler.Implementation.AssemblyCompiler.CompileAssembly(IReadOnlyCollection`1 syntaxTrees, IReadOnlyCollection`1 externalAssemblyLocations, OpenApiOutputModel openApiOutputModel, String outputBinaryFolder, String outputAssemblyName, String assemblyNamespace, TargetEnum target)
   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Implementation\FunctionCompiler.cs:line 86
   at FunctionMonkey.Compiler.Program.Main(String[] args) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Program.cs:line 47
C:\Users\cchat\.nuget\packages\functionmonkey.compiler\2.3.1\build\netstandard1.0\FunctionMonkey.Compiler.targets(21,5): error MSB3073: The command "dotnet "C:\Users\cchat\.nuget\packages\functionmonkey.compiler\2.3.1\build\netstandard1.0\..\..\tools\netcoreapp2.1/FunctionMonkey.Compiler.dll" "D:\Cheranga\Learning\Azure\Serverless\FunkyTodo\FunkyTodo.Api\bin\Debug\netcoreapp2.1\bin\FunkyTodo.Api.dll" --netcore21" exited with code -532462766.`

* These are the packages which has been installed in the project

![image](https://user-images.githubusercontent.com/4554283/59136309-e11f5380-89c5-11e9-812d-60baac3f467b.png)

* This is my function app configuration

```CSharp
    public class FunctionAppConfiguration : IFunctionAppConfiguration
    {
        public void Build(IFunctionHostBuilder builder)
        {
            builder.Setup((services, commandRegistry) =>
                {
                    //
                    // Register the validators
                    //
                    services.AddTransient<IValidator<CreateTodoCommand>, CreateTodoCommandValidator>();
                    //
                    // Register the repositories
                    //
                    services.AddSingleton<ITodoRepository, InMemoryTodoRepository>();
                    //
                    // Register the command handlers
                    //
                    commandRegistry.Discover(this.GetType().Assembly);
                })
                .AddFluentValidation()
                .OpenApiEndpoint(apiBuilder =>
                {
                    apiBuilder.Title("Funky Monkey API")
                        .Version("1.0.0")
                        .UserInterface();
                })
                .Functions(functionBuilder =>
                {
                    functionBuilder.HttpRoute("/api/v1/todos/", route =>
                    {
                        route.HttpFunction<CreateTodoCommand>(AuthorizationTypeEnum.Function, HttpMethod.Post)
                            .OutputTo.ServiceBusQueue("ServiceBusConnection","myq");
                            //.Options(options => options.ResponseHandler<CreateTodoItemResponseHandler>());
                    });
                });
        }
    }
```

* Also, I have included the necessary connection strings in the `local.settings.json`

```JSON
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard": "UseDevelopmentStorage=true",
    "ServiceBusConnection": "[MY CONNECTION STRING GOES HERE]",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```

* The command and the command handlers are as shown below,

```CSharp
    public class CreateTodoCommand : ICommand<TodoDisplay>
    {
        public string Description { get; set; }
        public bool IsCompleted { get; set; }
    }

    internal class CreateTodoCommandHandler : ICommandHandler<CreateTodoCommand, TodoDisplay>
    {
        private readonly ITodoRepository _repository;

        public CreateTodoCommandHandler(ITodoRepository repository)
        {
            _repository = repository;
        }

        public async Task<TodoDisplay> ExecuteAsync(CreateTodoCommand command, TodoDisplay previousResult)
        {
            var todo = new Todo
            {
                Id = Guid.NewGuid().ToString(),
                Description = command.Description,
                IsCompleted = command.IsCompleted,
                CreatedDate = DateTime.UtcNow
            };

            var createdTodo =await _repository.AddTodoAsync(todo);

            return new TodoDisplay
            {
                Description = createdTodo.Description,
                IsCompleted = createdTodo.IsCompleted
            };
        }
    }
```

**Comment by Cheranga** [comment]
I have not included the package `Microsoft.Azure.WebJobs.ServiceBus`. I included it, but still cannot build. It has the same error as shown in above, but also it mentions that the package versions does not match.

`D:\Cheranga\Learning\Azure\Serverless\FunkyTodo\FunkyTodo.Api\FunkyTodo.Api.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.Azure.WebJobs.ServiceBus 2.3.0 requires Microsoft.Azure.WebJobs (= 2.3.0) but version Microsoft.Azure.WebJobs 3.0.9 was resolved.
D:\Cheranga\Learning\Azure\Serverless\FunkyTodo\FunkyTodo.Api\FunkyTodo.Api.csproj : warning NU1701: Package 'Microsoft.Azure.ServiceBus.EventProcessorHost 2.2.10' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
D:\Cheranga\Learning\Azure\Serverless\FunkyTodo\FunkyTodo.Api\FunkyTodo.Api.csproj : warning NU1701: Package 'Microsoft.Azure.WebJobs.ServiceBus 2.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
D:\Cheranga\Learning\Azure\Serverless\FunkyTodo\FunkyTodo.Api\FunkyTodo.Api.csproj : warning NU1701: Package 'WindowsAzure.ServiceBus 3.4.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
ClassLibrary1 -> D:\Cheranga\Learning\Azure\Serverless\FunkyTodo\ClassLibrary1\bin\Debug\netstandard2.0\ClassLibrary1.dll
FunkyTodo.Api -> D:\Cheranga\Learning\Azure\Serverless\FunkyTodo\FunkyTodo.Api\bin\Debug\netcoreapp2.1\bin\FunkyTodo.Api.dll`

**Comment by JamesRandall** [comment]
Are you building against framework 4.x?
Azure Functions v2 is only supported on .NET Core per the below:
https://feedback.azure.com/forums/355860-azure-functions/suggestions/34148206-azure-functions-v2-supporting-the-net-framewor

**Comment by Cheranga** [comment]
Hi @JamesRandall ,
No, I am using the V2 environment.

**Comment by JamesRandall** [comment]
Looking at the version numbers I believe this is to do with the version of the service bus packages you have registered.

You need Microsoft.Azure.WebJobs.Extensions.Storage 3.x.x installed and this in turn needs a Microsoft.Azure.ServiceBus 3.x installed. I'm running on 3.1.0-beta3 and 3.0.2 respectively in my Function Monkey dev branch.
