### ISSUE TITLE
OpenApi - Describing Parameters

### ISSUE THREAD

**Issue by ArryMatt** [JamesRandall/FunctionMonkey#80]
I'm using OpenAPI, which is amazing, especially as it's so very little code.

It's helping the consumer of my API massively, but they are coming back with questions about the specifics of some of the parameters, like UserSites, which is a List<string>, asking if that is SiteId or Site Name.  

I could add a description to the function, but I see OpenAPI allows for describing parameters individually, is there anyway to get this into FunctionMonkey?

**Comment by JamesRandall** [comment]
I can add that fairly straightforwardly. Will do so on next release.

**Comment by MarkusBernhardt** [comment]
Hi Arry,
could you please look into the pull request #102, whether this would fit your needs?
Best regards,
Markus

**Comment by JamesRandall** [comment]
PR merged.
