### ISSUE TITLE
Compilation Error for Newton.Json dependency

### ISSUE THREAD

**Issue by davidjsteele** [JamesRandall/FunctionMonkey#84]
Hi James, 

Setup
**DotnetSdk 2.1**
**Azure functions v2** 
On build I'm seeing the below NewtonSoft dependency error below.  I note https://github.com/JamesRandall/FunctionMonkey/issues/8 but seems to have reared its head again.

Current nugets in use:
![image](https://user-images.githubusercontent.com/7621977/63340011-0a514e00-c33e-11e9-906f-0e372dc79833.png)

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file.

Anything obvious I'm doing wrong?

**Comment by JamesRandall** [comment]
Hi, could you try it with Newtonsoft.Json 11.0.2 and let me know if that helps please?

**Comment by davidjsteele** [comment]
Hi James, 
Think this is related.  https://github.com/reactiveui/refit/issues/670
Trying to resolve but downgrading Refit version, currently in dependency hell

**Comment by JamesRandall** [comment]
Yeah I thought it would be something like that.
Azure Functions is a bit of a nightmare with dependencies. It's much much better than it was but the whole "in process with their deployed runtime" stuff continues to burn.

**Comment by davidjsteele** [comment]
Thanks James, 
So for anyone else...
![image](https://user-images.githubusercontent.com/7621977/63346252-78047680-c34c-11e9-8c40-d02221894b8a.png)
These versions of Refit Nuget packages seem to work.

Any plans on supporting NewtonSoft => 12.0 James?

**Comment by JamesRandall** [comment]
I'm not sure its anything I can do anything about myself - the problem is in the Azure Functions runtime. They have relaxed the dependency requirement but its still causing issues I see. It sounds like their is more work in progress and the .30 version of Functions is in beta so maybe this will address it.

Worth reading this thread: https://github.com/Azure/azure-functions-host/issues/4049

And the below highlight:

> For runtime binding behavior in 2.x: Currently, the runtime unifies (Json.NET specifically) to the version it uses (currently, 11.x), which enables redirection and is only problematic in the cases where functions or dependencies take a dependency on new functionality (which is the case for some of the issues reported above). We're tracking a fix for this as well, but this last item has to be carefully handled to ensure a good experience and make sure existing apps are not negatively impacted.

I'll track it and once resolved make sure FM is ok.

**Comment by davidjsteele** [comment]
Apologies, should have realised the dependency was on the framework and not the product.
Great work BTW, really like the idea of the CQS approach coupled with TDD.  Fits nicely into our real estate and follows best practices too :)

**Comment by JamesRandall** [comment]
No worries! It's not always obvious what's going on with dependencies at the best of times and when you add the Functions runtime into the mix.... well!
