### ISSUE TITLE
Access to ExecutionContext in ITokenValidator implementation

### ISSUE THREAD

**Issue by nigelbasel** [JamesRandall/FunctionMonkey#9]
At present the http.csharp.handlebars template only sets up the Context Setter just prior to executing the Command. It would be extremely useful to have access to the Context from inside the ITokenValidator.ValidateAsync method. 

If we moved the code that sets the Execution Context (currently line 118)  to an earlier point (say Line 40) then the execution context would be available to all the code that runs from there on out .

**Comment by JamesRandall** [comment]
Makes sense, I'll look to move it.

**Comment by JamesRandall** [comment]
This should land in the next release (v0.15.0) that I have underway. I'd hoped to push it out as part of 0.14.0 that has just released but I really needed to get an urgent fix out.

**Comment by JamesRandall** [comment]
This is now available in 0.15.3 that is indexing on NuGet now.
