### ISSUE TITLE
EventHub Output Binding

### ISSUE THREAD

**Issue by jeckyl2010** [JamesRandall/FunctionMonkey#90]
Hi.

I'm looking around for the EventHub Output Binding, but can't seem to find it and scanning through the codebase does not reveal much to me :).

Is EventHub Output Binding supported. If not, is there a way to mix FunctionMonkey with an attribute based EventHub output, maybe something like

FunctionMonkey(IN)::HttpTrigger --> FunctionMonkey(OUT)::StorageQueue --> AzureFunction(IN)::StorageQueue --> AzureFunction(OUT)::EventHub

Thanks in advance

**Comment by JamesRandall** [comment]
Its mostly coded up but I haven't released it - I plan on doing so in the v4.x series which is under development at the moment.

**Comment by JamesRandall** [comment]
Included in commit 7940add , scheduled for release in beta2 today.
