### ISSUE TITLE
FunctionMonkey.TokenValidator.Implementation.TokenValidator issues

### ISSUE THREAD

**Issue by alexeymarkov** [JamesRandall/FunctionMonkey#94]
Hello,

1. In case of invalid JWT it thrown an exception and a function returns 500 but it should return 404 (with logging of an original exception).
To fix it add
```
catch (ArgumentException e)
{
	return null;
}
```
because _ArgumentException_ is thrown when _CanReadToken_ returns _false_.

2.
```
catch (SecurityTokenSignatureKeyNotFoundException)
{
	Configuration.ConfigurationManager.RequestRefresh();
	num++;
}
```
it seems in this case the configuration won't be updated because `await Configuration.ConfigurationManager.GetConfigurationAsync(CancellationToken.None)` is called outside of the loop.

3. Exceptions are also not caught when calling `await Configuration.ConfigurationManager.GetConfigurationAsync(CancellationToken.None)`. This means a function will return 500 but I think it should return 404 (eventually with logging of an original exception).

**Comment by alexeymarkov** [comment]
If you are agree I could apply fixes and provide a PR :-)

**Comment by JamesRandall** [comment]
Agree they are all issues. If you can easily do a PR please do - otherwise give me a couple of days and I'll get these addressed.

**Comment by alexeymarkov** [comment]
PR: https://github.com/JamesRandall/FunctionMonkey/pull/96

**Comment by JamesRandall** [comment]
Thanks for the PR - now merged.
